name: EDU ci example

on:
  repository_dispatch:

env: 
  pull_req_url: ${{github.event.client_payload.pull_request_url}} 
  token: ${{github.event.client_payload.token_csrf}} 
  github_token: ${{github.event.client_payload.github_token}}
  task_id: ${{github.event.client_payload.task_id}} 
  adapter_url: ${{github.event.client_payload.adapter_url}}
  task_score: 0 
  max_score: 0 
  status: Done

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    
    - name: Clone student repository
      run: |
        tree
        sudo git clone ${{env.pull_req_url}} student_work
        sudo chmod -R 777 ./student_work
        tree     
        
    - name: Install dependences
      working-directory: student_work
      run: |
        go mod download
        go mod tidy

    # INSERT YOUR CODE HERE
    # INSERT YOUR CODE HERE
    # INSERT YOUR CODE HERE
    # INSERT YOUR CODE HERE

    - name: Test
      run: go test -v ./...
      
    - name: Hello edu, i'm coming for you
      if: ${{ always() }}
      run: |
        curl \
        -X PUT \
        -H "Accept: application/vnd.github.v3+json" \
        ${{ env.adapter_url }} \
        -d '{"token_csrf":"${{ env.token}}", \
        "ci_score":${{env.task_score}}, \
        "ci_max_score":${{env.max_score}}, \
        "ci_status":"${{env.status}}" }'

